mongo:
  image: mongo
  environment:
    SERVICE_NAME: mongo
    SERVICE_TAGS: simple
  ports:
    - "27017:27017"

simpleapp:
  build: ./go-docker-simpleapp
  ports:
    - "8080"
  dns:
    - <YOUR DOCKER0>
  dns_search: service.consul
  environment:
    DATABASE_PORT_27017_TCP_ADDR: mongo
    DB_NAME: TEST
    SERVICE_NAME: app
    SERVICE_TAGS: simple

consul:
  command: -server -bootstrap
  image: progrium/consul:latest
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
    - "<YOUR DOCKER0>:53:53/udp"

registrator:
  command:  -ip=<YOUR DOCKER HOST IP> consul://consul:8500
  image: gliderlabs/registrator:latest
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - consul

lb:
  build: ./lb
  links:
    - consul
  ports:
    - "80:80"
  environment:
    CONSUL_URL: consul:8500
